//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HallsBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingId { get; set; }
        public Nullable<int> HallId { get; set; }
        public string HallName { get; set; }
        public string FunctionType { get; set; }
        public Nullable<bool> Decaration { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> BookedOn { get; set; }
    }
}
